## Numpy
for array creation and numerical calculation. it got its name "NUMPY" from "Numerical Python"


In [4]:
#importing the numpy library
import numpy as np


In [3]:
#using array()
array_1d =numpy.array([1,2,3,4])    #1 dim array
array_2d =numpy.array([[1,2],[3,4]]) #2dim array


In [10]:
#using alias and array() function
array_1d =np.array([1,2,3,4])    #1 dim array
array_2d =np.array([[1,2],[3,4]]) #2dim array

the arange() is specifically for array , although have the behaviour of the range() function.

In [16]:
#print even nos
array_range = np.arange(0,10,2)

print(array_range)

[0 2 4 6 8]


In [15]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [17]:
#creating a zero array
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#ones array
ones_array = np.ones((2,2))
ones_array

array([[1., 1.],
       [1., 1.]])

In [22]:
#bitwise operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
sum_array = array_a + array_b 

sum_array


array([5, 7, 9])

if the length of the array is unequal it will result in  an error. there shape must match

In [23]:
array_a = np.array([1, 2, 3, 5,8,6])
array_b = np.array([4, 5, 6])
sum_array = array_a + array_b 

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

## Note:
the shape of an array takes into account the number of rows and column

1. A 1-dim array is made up of scalar quantities

2. A 2-dim array is made up of one-dim array

3. A 3-dim array is made up of two-dim array

Hence, Generally  an n-dim array will have its element as (n-1)dim array

In [26]:
array_a = np.array([1, 2, 3, 5,8,6])
array_b = np.array([4, 5, 6])

#shapes
print(array_a.shape)
print(array_b.shape)

(6,)
(3,)


Array of Zeros is called zeros in numpy

In [57]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
print(zeros_array.shape)
print(zeros_array.ndim)

(3, 3)
2


In [54]:
zero_arr = np.zeros((4,4))
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
#identity matrix
idm = np.eye(3,3)
idm

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
bool_val = idm.astype(bool)
bool_val

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
arr_num = np.array([[1,2,3],
                    [4,5,6]])
#indexing 
print(arr_num[0,1])
print(arr_num.shape)

2
(2, 3)


In [47]:
arr_num[1,2]

6

In [48]:
arr_num[0,0]

1

In [49]:
add_arr = arr_num[0,2] + arr_num[1,1]
print(add_arr)

8


In [50]:
arr = np.array([1, 2, 3, 4])
print(arr[3] - arr[0])

3


In [ ]:
arr3 = np.arry([[3,5,2],
               [1,2,0],
               [7,3,9]])
#what is the shape and the dimension of the array
#calculate arr3[2,1] + arr3[0,2]

In [65]:
#write an array that takes a range of numbers between 0 and 50 with an interval of 2:
num1 = [i for i in range(0,50,2)]
num1i = [i for i in np.arange(0,50,2)]
print(num1)
print(num1i)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


In [66]:
num1_arr = np.array([i for i in range(0,50,2)])
num1_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

ASSIGNMENT
create a numpy array that has the following shapes
1.
(a) 6, 5, 3

(b) 1

(c) 1,1,1,1

(d) 2,2,1

2.  arr_num = [[2,3,4],
               [5,0.7,9],
               [3,1, 0.8]]
    (a). multiply arr_num by its identity matrix  (hint: identity matrix is a matrix that have it diagonal as 1 while other sides are zeros. ask google for more infor)
    (b) find the dimension and the shape