In [1]:
import numpy as np

In [2]:
#join using concatenate (Horizontal)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr_n = np.concatenate((arr1, arr2), axis=1)
print(arr_n)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
arr_a =np.array([[2,4,6], [8,10,12]])
arr_b =np.array([[9,3,1], [6,2,10]])
sum_arr =np.concatenate((arr_a, arr_b), axis=1)
print(sum_arr)

[[ 2  4  6  9  3  1]
 [ 8 10 12  6  2 10]]


In [5]:
sum_arr.shape

(2, 6)

In [6]:
sum_arr.ndim

2

In [7]:
#join or combine two or more array (stack ... (vertical))
arr_a =np.array([[2,4,6], [8,10,12]])
arr_b =np.array([[9,3,1], [6,2,10]])

comb_arr = np.stack((arr_a, arr_b), axis=1)

print(comb_arr)

[[[ 2  4  6]
  [ 9  3  1]]

 [[ 8 10 12]
  [ 6  2 10]]]


In [8]:
comb_arr.shape

(2, 2, 3)

In [9]:
comb_arr.ndim

3

In [10]:
#hstack is in single series
arr_a = np.array([1, 2, 3])

arr_b = np.array([4, 5, 6])

arr = np.hstack((arr_a, arr_b))

print(arr)

[1 2 3 4 5 6]


In [11]:
arr.shape

(6,)

In [12]:
arr.ndim

1

convert arr_a = [[2,3],[4,5]]  and arr_b = [[6,8],[4,9]] into a single array using hstack

In [15]:

arr_a = [[2,3,4,5]]
arr_b = [[6,8,4,9]]
arr_m = np.hstack((arr_a, arr_b))
print(arr_m)

[[2 3 4 5 6 8 4 9]]


In [18]:
new= np.squeeze(arr_m)
new

array([2, 3, 4, 5, 6, 8, 4, 9])

In [20]:
new.reshape(2,4)

array([[2, 3, 4, 5],
       [6, 8, 4, 9]])

In [17]:
#Stacking Along Height (depth)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [21]:
arr.shape

(1, 3, 2)

In [23]:
arr_a = np.array([2,5,3])
arr_b = np.array([3,2,9])
arr_c = np.array([5,4,8])

arr_j =np.dstack((arr_a,arr_b,arr_c))
print(arr_j)

[[[2 3 5]
  [5 2 4]
  [3 9 8]]]


In [24]:
arr_p =np.hstack((arr_a,arr_b,arr_c))
print(arr_p)

[2 5 3 3 2 9 5 4 8]


# Splitting NumPy Arrays
Splitting is opposite operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [30]:
arr4 = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr4, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [35]:
## create an array of  numbers from 0 to 50 and split the array into 4 new arrays
comb_arr = np.array([i for i in np.arange(0,50)])
new= np.array_split(comb_arr, 4)
new

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]),
 array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]),
 array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]

In [37]:
new[2]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [38]:
new[2][6]

32

In [40]:
new[0][2]

2

note that: rsplit() , split()  is different array_split()

classwork create an array that generates 80 random integers, use the array_split() to split them into 6 new arrays

In [42]:
import random
arr1= np.array([i for i in range(80)   if i>= random.randint(1,9)])
arr1

array([ 3,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79])

In [43]:
np.array_split(arr1, 6)

[array([ 3,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
 array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]),
 array([56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]),
 array([68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])]