In [1]:
import numpy as np

In [2]:
#join using concatenate (Horizontal)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr_n = np.concatenate((arr1, arr2), axis=1)
print(arr_n)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
arr_a =np.array([[2,4,6], [8,10,12]])
arr_b =np.array([[9,3,1], [6,2,10]])
sum_arr =np.concatenate((arr_a, arr_b), axis=1)
print(sum_arr)

[[ 2  4  6  9  3  1]
 [ 8 10 12  6  2 10]]


In [4]:
sum_arr.shape

(2, 6)

In [5]:
sum_arr.ndim

2

In [6]:
#join or combine two or more array (stack ... (vertical))
arr_a =np.array([[2,4,6], [8,10,12]])
arr_b =np.array([[9,3,1], [6,2,10]])

comb_arr = np.stack((arr_a, arr_b), axis=1)

print(comb_arr)

[[[ 2  4  6]
  [ 9  3  1]]

 [[ 8 10 12]
  [ 6  2 10]]]


In [7]:
comb_arr.shape

(2, 2, 3)

In [8]:
comb_arr.ndim

3

In [9]:
#hstack is in single series
arr_a = np.array([1, 2, 3])

arr_b = np.array([4, 5, 6])

arr = np.hstack((arr_a, arr_b))

print(arr)

[1 2 3 4 5 6]


In [10]:
arr.shape

(6,)

In [11]:
arr.ndim

1

convert arr_a = [[2,3],[4,5]]  and arr_b = [[6,8],[4,9]] into a single array using hstack

In [12]:

arr_a = [[2,3,4,5]]
arr_b = [[6,8,4,9]]
arr_m = np.hstack((arr_a, arr_b))
print(arr_m)

[[2 3 4 5 6 8 4 9]]


In [13]:
new= np.squeeze(arr_m)
new

array([2, 3, 4, 5, 6, 8, 4, 9])

In [14]:
new.reshape(2,4)

array([[2, 3, 4, 5],
       [6, 8, 4, 9]])

In [15]:
#Stacking Along Height (depth)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [16]:
arr.shape

(1, 3, 2)

In [17]:
arr_a = np.array([2,5,3])
arr_b = np.array([3,2,9])
arr_c = np.array([5,4,8])

arr_j =np.dstack((arr_a,arr_b,arr_c))
print(arr_j)

[[[2 3 5]
  [5 2 4]
  [3 9 8]]]


In [18]:
arr_p =np.hstack((arr_a,arr_b,arr_c))
print(arr_p)

[2 5 3 3 2 9 5 4 8]


# Splitting NumPy Arrays
Splitting is opposite operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [20]:
arr4 = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr4, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [21]:
## create an array of  numbers from 0 to 50 and split the array into 4 new arrays
comb_arr = np.array([i for i in np.arange(0,50)])
new= np.array_split(comb_arr, 4)
new

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]),
 array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]),
 array([38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]

In [22]:
new[2]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [23]:
new[2][6]

32

In [24]:
new[0][2]

2

note that: rsplit() , split()  is different array_split()

classwork create an array that generates 80 random integers, use the array_split() to split them into 6 new arrays

In [25]:
import random
arr1= np.array([i for i in range(80)   if i>= random.randint(1,9)])
arr1

array([ 2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79])

In [26]:
np.array_split(arr1, 6)

[array([ 2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]),
 array([43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]),
 array([56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]),
 array([68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])]

In [34]:
#scalar multiplication
arr_1 =np.array([3,4,5])
mult = arr_1 * 3
print(mult)


[ 9 12 15]


In [35]:
#vector multiplication
arr_1 =np.array([3,4,5])
arr_2 =np.array([2,6,7])
multi = arr_1 * arr_2
multi

array([ 6, 24, 35])

In [46]:
import random
x = random.randint(1,21)
print(x)

2


## Filtering numpy

In [51]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for i in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if i >= 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, True, True]
[42 43 44]


In [54]:
from numpy import random
#have the ability to make 4 choices in 3 rows and 5columns
x = random.choice([3, 5, 7, 9], size=(3, 5)) 

print(x)

[[9 9 3 5 5]
 [3 5 3 7 9]
 [7 9 7 3 7]]


In [58]:
#random permutation
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr )


[2 4 1 5 3]


## Introduction to Pandas 

In [63]:
#how to create a dataframe
import pandas as pd
mycars = {
  'cars': ["Mustang", "BMW", "Benz"],
  'passings': [3, 7, 2]
}
myvar = pd.DataFrame(mycars)
print(myvar)


      cars  passings
0  Mustang         3
1      BMW         7
2     Benz         2


In [64]:
#creating a larger dataframe
employee_data = {
    'Name': ['Edward', 'Precious', 'Michael', 'Gabriel', 'Nikson', 'Faith', 'Comfort'],
    'Age': [29,28, 31,19,34,25,23],
    'Salary': [34000 ,  39000, 45000, 90000, 24000,34000, 120000],
    'Location': ['Badagry', 'Warri', 'Sapele','Port Harcourt', 'Eleme', 'Lekki', 'Eket']
}

emp_data = pd.DataFrame(employee_data)
emp_data

Name  Age  Salary       Location
0    Edward   29   34000        Badagry
1  Precious   28   39000          Warri
2   Michael   31   45000         Sapele
3   Gabriel   19   90000  Port Harcourt
4    Nikson   34   24000          Eleme
5     Faith   25   34000          Lekki
6   Comfort   23  120000           Eket

In [62]:
#how to create a pandas series
data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(data)


a    10
b    20
c    30
d    40
dtype: int64


In [66]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)
df

calories  duration
0       420        50
1       380        40
2       390        45

In [68]:
#displaying a CSV file in pandas
import pandas as pd
path_csv = r"C:\Users\pc\Documents\mic_folder\divine\divine\datasets\washington.csv"

df = pd.read_csv(path_csv)



In [70]:
df.head()

Unnamed: 0           Start Time             End Time  Trip Duration  \
0     1621326  2017-06-21 08:36:34  2017-06-21 08:44:43        489.066   
1      482740  2017-03-11 10:40:00  2017-03-11 10:46:00        402.549   
2     1330037  2017-05-30 01:02:59  2017-05-30 01:13:37        637.251   
3      665458  2017-04-02 07:48:35  2017-04-02 08:19:03       1827.341   
4     1481135  2017-06-10 08:36:28  2017-06-10 09:02:17       1549.427   

                                 Start Station                   End Station  \
0                         14th & Belmont St NW                15th & K St NW   
1                   Yuma St & Tenley Circle NW  Connecticut Ave & Yuma St NW   
2               17th St & Massachusetts Ave NW                 5th & K St NW   
3             Constitution Ave & 2nd St NW/DOL    M St & Pennsylvania Ave NW   
4  Henry Bacon Dr & Lincoln Memorial Circle NW         Maine Ave & 7th St SW   

    User Type  
0  Subscriber  
1  Subscriber  
2  Subscriber  
3    Customer  
4  Subscriber

In [77]:
#displaying an excel file in pandas
path_excel = "C:/Users/pc/Downloads/dataset/work_stuff/retail_data_dirty.xlsx"

df1 = pd.read_excel(path_excel)

In [78]:
df1

Transaction_ID       Date Customer_ID  Product_ID  Units_Sold  \
0          TXN000000 2023-11-03    CUST5695         177         9.0   
1          TXN000001 2023-03-30    CUST1035         107         6.0   
2          TXN000002 2023-08-27    CUST4216         190         8.0   
3          TXN000003 2023-02-07    CUST8870         195         3.0   
4          TXN000004 2023-12-27    CUST4105         105         5.0   
...              ...        ...         ...         ...         ...   
99995      TXN099995 2023-10-15    CUST8506         174         6.0   
99996      TXN099996 2023-09-01    CUST5770         182         9.0   
99997      TXN099997 2023-07-21    CUST3064         189         8.0   
99998      TXN099998 2023-01-12    CUST5691         197         8.0   
99999      TXN099999 2023-01-13    CUST2342         119         9.0   

       Sale_Amount Store_Name  
0              NaN      Alpha  
1            91.44      Gamma  
2           785.16       Beta  
3           286.08      Alpha  
4           688.16      Alpha  
...            ...        ...  
99995       904.82      Delta  
99996       414.89       Beta  
99997        86.37       Beta  
99998       355.81      Alpha  
99999       389.38      Delta  

[100000 rows x 7 columns]

In [76]:
df2 = pd.read_excel(path_excel, sheet_name="Product_Info" )
df2

Product_ID Product_Name     Category    Price Discontinued
0          100      Monitor  Accessories   232.78          yes
1          101      Monitor       Office  1163.09            N
2          102      Printer       Office   202.45            N
3          103       Laptop  Electronics   375.07          Yes
4          104       Laptop       Office  1262.60          Yes
..         ...          ...          ...      ...          ...
95         195       Tablet  Electronics   452.92           no
96         196        Phone       Office  1213.68            Y
97         197      Printer  Electronics  1430.06           No
98         198      Printer  Electronics  1436.76            Y
99         199       Tablet       Office   203.64           no

[100 rows x 5 columns]