
## slicing numpy array¶
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [4]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1[1:6]

array([2, 3, 4, 5, 6])

In [6]:
arr1[:5]

array([1, 2, 3, 4, 5])

In [7]:
arr1[0:5]

array([1, 2, 3, 4, 5])

In [8]:
arr1[:5]==arr1[0:5]

array([ True,  True,  True,  True,  True])

In [10]:
#Negative indexing in array slicing
arr1[-4:-1]

array([3, 4, 5])

In [13]:
#reverse the array
arr1[::-1]

array([6, 5, 4, 3, 2, 1])

In [14]:
#slicing 2d array
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
arr2[0,2:]

array([3, 4, 5])

In [22]:
arr2[1,::-1]

array([10,  9,  8,  7,  6])

In [23]:
arr2[1, 2:-1]

array([8, 9])

In [24]:
arr2[1, 2:]

array([ 8,  9, 10])

In [26]:
arr_num = np.array([[[[2,3], [3,9]]]])
arr_num

array([[[[2, 3],
         [3, 9]]]])

In [27]:
arr_num.ndim

4

In [28]:
arr_num.shape

(1, 1, 2, 2)

In [31]:
new_arr= np.squeeze(arr_num)
new_arr

array([[2, 3],
       [3, 9]])

In [32]:
new_arr.shape

(2, 2)

In [33]:
new_arr.ndim

2

In [34]:
new_arr

array([[2, 3],
       [3, 9]])

In [39]:
# Transforming Arrays using reshape and squeeze 

In [37]:
new_arr.reshape(1,4)

array([[2, 3, 3, 9]])

In [41]:
new_arr.reshape(4,1)

array([[2],
       [3],
       [3],
       [9]])

The squeeze function is used to remove redundant dimensions 

while the reshape function is used for transformation of the array, especially its orientation

## class work
1.ar_a= [[[[2,3,5],[12,4,3],[4,9,8]]]]

2.ar_b= [[1,2],[3,4]]

obtain their shape, dimension, squeeze and reshape the arrays

In [44]:
#1 
ar_a = np.array([[[[2,3,5],[12,4,3],[4,9,8]]]])
ar_a

array([[[[ 2,  3,  5],
         [12,  4,  3],
         [ 4,  9,  8]]]])

In [45]:
ar_a.ndim

4

In [47]:
ar_a.shape

(1, 1, 3, 3)

In [51]:
new_ar = np.squeeze(ar_a)
new_ar

array([[ 2,  3,  5],
       [12,  4,  3],
       [ 4,  9,  8]])

In [60]:
new_ar.reshape(9,1)

array([[ 2],
       [ 3],
       [ 5],
       [12],
       [ 4],
       [ 3],
       [ 4],
       [ 9],
       [ 8]])

In [59]:
new_ar.reshape(1,9)

array([[ 2,  3,  5, 12,  4,  3,  4,  9,  8]])

In [61]:
# 2. 
ar_b= np.array([[1,2],[3,4]])
ar_b

array([[1, 2],
       [3, 4]])

In [62]:
ar_b.shape

(2, 2)

In [63]:
ar_b.ndim


2

In [71]:
new1_ar = np.squeeze(ar_b)
new1_ar

array([[1, 2],
       [3, 4]])

In [69]:
new1_ar.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [67]:
new1_ar.reshape(1,4)

array([[1, 2, 3, 4]])

## View and copy in numpy Arrays

In [82]:
#View
arr = np.array([1, 2, 3, 4, 5]) 
x = arr.view()
arr[3] = 42

print(arr)
print(x)

[ 1  2  3 42  5]
[ 1  2  3 42  5]


In [81]:
#copy
arr = np.array([1, 2, 3, 4, 5]) 
x = arr.copy()
arr[4] = 42

print(arr)
print(x)

[ 1  2  3  4 42]
[1 2 3 4 5]


In your own words what is the difference between view and copy?